---
- name: APT Dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-pip"
    - "python-psycopg2"  
    - "tar"    

- name: PIP Dependencied
  pip:
    name: "{{ item }}"
  with_items:
    - "powa-collector"
    
- name: Download the latest release on pypi
  get_url:
    url: https://pypi.io/packages/source/p/powa-collector/powa-collector-0.0.1.tar.gz
    dest: /tmp/powa-collector.tar.gz
    mode: '0660'
    
- name: Extract powa-collector.tar.gz
  unarchive:
    src: /tmp/powa-collector.tar.gz
    dest: /tmp/powa-collector
 