---
- name: APT Dependencies
  apt:
    name: ['python-pip', 'python-psycopg2', 'tar']
    state: present
  
- name: PIP Dependencied
  pip:
    name: ['powa-collector']
    
- name: Extract powa-collector.tar.gz
  unarchive:
    src: https://pypi.io/packages/source/p/powa-collector/powa-collector-0.0.1.tar.gz
    dest: /tmp
    remote_src: yes
 