---

postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgresql_apt_repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

patroni_postgresql_data_dir: "/var/lib/patroni"
patroni_postgresql_config_dir: "/var/lib/patroni"
patroni_postgresql_bin_dir: "/usr/lib/postgresql/{{ patroni_postgresql_version }}/bin"
patroni_postgresql_pgpass: "{{ patroni_postgresql_data_dir }}/.pgpass"
patroni_bin_dir: /usr/local/bin

patroni_postgresql_packages:
  - { name: "postgresql-{{ patroni_postgresql_version }}",            state: "present" }
  - { name: "postgresql-client-{{ patroni_postgresql_version }}",     state: "present" }
  - { name: "postgresql-contrib-{{ patroni_postgresql_version }}",    state: "present" }
  - { name: "postgresql-server-dev-{{ patroni_postgresql_version }}", state: "present" }

patroni_system_packages:
  - { name: "python-psycopg2", state: "present" }
  - { name: "python-pip",      state: "present" }
  - { name: "jq",              state: "present" }
